repos:
  - repo: https://github.com/floatingpurr/sync_with_poetry
    rev: 0.4.0
    hooks:
      - id: sync_with_poetry
        args: ["--db", "pre_commit_sync.json"]
        stages: [commit]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-toml
        stages: [manual, commit]
      - id: check-yaml
        stages: [manual, commit]
      - id: check-json
        stages: [manual, commit]
      - id: end-of-file-fixer
        stages: [manual, commit]
      - id: trailing-whitespace
        stages: [manual, commit]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.254
    hooks:
      - id: ruff
        language: system
        stages: [commit]

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        language: system
        stages: [commit]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.1.1
    hooks:
      - id: mypy
        language: system
        stages: [commit]
