name: Update Pre-Commit Sync File

env:
  VENV: .venv/bin/activate

on:
  push:
    branches: [
      "renovate/ruff-**",
      "renovate/mypy-**",
    ]
  pull_request:
    branches: [
      "renovate/ruff-**",
      "renovate/mypy-**",
    ]

jobs:
  update-pre-commit-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install Dev Dependencies
        run: poetry install --only=dev --no-interaction

      - name: Run Pre-Commit Checks
        uses: pre-commit/action@v3.0.0
        continue-on-error: true
        with:
          extra_args: --hook-stage manual --all-files

      - name: Commit Fixes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update tool versions in pre-commit file"
          git push
