name: Update Pre-Commit Sync File

env:
  VENV: .venv/bin/activate

on:
  push:
    branches: [
      "renovate/ruff-**",
      "renovate/mypy-**",
    ]
  pull_request:
    branches: [
      "renovate/ruff-**",
      "renovate/mypy-**",
    ]

jobs:
  update-pre-commit-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install Dev Dependencies
        run: poetry install --only=dev --no-interaction

      - name: Run Pre-Commit Checks
        uses: pre-commit/action@v3.0.1
        continue-on-error: true
        with:
          extra_args: --hook-stage manual --all-files

      - name: Commit Fixes
        run: |
          if git diff --exit-code; then
            echo "No changes found."
          else
            git config user.name RenovateBot
            git config user.email renovatebot@swole.com
            git add .
            git commit -m "Update tool versions in pre-commit file"
            git push
          fi
