name: "Renovate Bot"

on:
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: '0/15 * * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Swole V2 Repo
        uses: actions/checkout@v3.3.0

      - name: Run Renovate Bot
        uses: renovatebot/github-action@v36.0.0
        with:
          renovate-version: 35.0.0
          configurationFile: ./renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: 'debug'
