name: Smokeshow

on:
  workflow_run:
    workflows: [ Test ]
    types: [ completed ]

permissions:
  statuses: write

jobs:
  smokeshow:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Smokeshow
        run: pip install smokeshow

      - name: Download Artificat from Test Workflow
        uses: dawidd6/action-download-artifact@v2.26.0
        with:
          workflow: test.yml
          commit: ${{ github.event.workflow_run.head_sha }}

      - name: Upload Coverage Artifact
        run: smokeshow upload coverage
        env:
          SMOKESHOW_GITHUB_STATUS_DESCRIPTION: Coverage {coverage-percentage}
          SMOKESHOW_GITHUB_COVERAGE_THRESHOLD: 99
          SMOKESHOW_GITHUB_CONTEXT: coverage
          SMOKESHOW_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SMOKESHOW_GITHUB_PR_HEAD_SHA: ${{ github.event.workflow_run.head_sha }}
          SMOKESHOW_AUTH_KEY: ${{ secrets.SMOKESHOW_AUTH_KEY }}
