name: Test and Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry==1.4.0

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Install Dev Dependencies
        run: poetry install --no-interaction

      - name: Install Just
        uses: extractions/setup-just@v1
        with:
          just-version: '1.13.0'

      - name: Install EdgeDB
        uses: edgedb/setup-edgedb@v1

      - name: Setup Test DB
        run: |
          db test init &&
          db test make-migration &&
          db test migrate

      - name: Check
        run: just check

      - name: Test
        run: just test
